In [ ]:
# Importujemy moduł torch, który jest podstawową biblioteką do obliczeń tensorowych w PyTorch.
import torch

# Importujemy klasę Tensor z modułu torch, która służy do tworzenia i manipulowania tensorami.
from torch import Tensor

: 

In [2]:
print("Wersja torch", torch.__version__)

Wersja torch 2.0.1


In [3]:
# Ustawiamy ziarno generatora liczb losowych w bibliotece PyTorch na 42.
# To pozwala na kontrolowane generowanie tych samych "losowych" liczb przy każdym uruchomieniu programu.
# Jest to przydatne do uzyskiwania powtarzalnych wyników w przypadku używania funkcji losowych.
torch.manual_seed(42)

In [4]:
# Tworzymy nowy tensor o wymiarach (2, 3, 4).
# Tensor ten ma trzy wymiary: 2, 3 i 4.
x = Tensor(2, 3, 4)
print(x)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [5]:
# Tworzymy tensor z listy podanych wartości
x = Tensor([[1, 2], [3, 4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [6]:
# Tworzymy nowy tensor o wymiarach (2, 3, 4) za pomocą funkcji torch.rand.
# Tensor ten jest wypełniony losowymi liczbami z zakresu [0, 1].
x = torch.rand(2, 3, 4)
print(x)

tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])


In [7]:
# Pobieramy wymiary tensora x za pomocą właściwości shape.
shape = x.shape
print("Wymiar tensora:", x.shape)

Wymiar tensora: torch.Size([2, 3, 4])


In [8]:
size = x.size()
print("Wymiar tensora:", size)

Wymiar tensora: torch.Size([2, 3, 4])


In [9]:
dim1, dim2, dim3 = x.size()
print("Wymiar:", dim1, dim2, dim3)

Wymiar: 2 3 4


In [10]:
import numpy as np

# Tablica w Numpy
np_arr = np.array([[1, 2], [3, 4]])
# Konwersja Numpy na Torch
tensor = torch.from_numpy(np_arr)

print("Numpy array:", np_arr)
print("PyTorch tensor:", tensor)

Numpy array: [[1 2]
 [3 4]]
PyTorch tensor: tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [11]:
tensor = torch.arange(4)
np_arr = tensor.numpy()

print("PyTorch tensor:", tensor)
print("Numpy array:", np_arr)

PyTorch tensor: tensor([0, 1, 2, 3])
Numpy array: [0 1 2 3]


In [12]:
# Obliczenia
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
y = x1 + x2

print("X1", x1)
print("X2", x2)
print("Y", y)

X1 tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])
X2 tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])
Y tensor([[1.0569, 0.3448, 1.2448],
        [0.7826, 0.8848, 0.8151]])


In [13]:
# Funkcja ta generuje sekwencję liczb od 0 do 5 (6 elementów).
x = torch.arange(6)
print("X", x)

X tensor([0, 1, 2, 3, 4, 5])


In [14]:
# Zmieniamy kształt tensora x z (6,) na (2, 3) za pomocą metody .view().
x = x.view(2, 3)
print("X", x)

X tensor([[0, 1, 2],
        [3, 4, 5]])


In [15]:
x = torch.arange(12).view(3, 4)
print("X", x)

X tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [16]:
# Druga kolumna
print(x[:, 1])

tensor([1, 5, 9])


In [17]:
# Pierwszy wiersz
print(x[0])

tensor([0, 1, 2, 3])


In [18]:
# Pierwsze dwa wiersze, ostatnia kolumna
print(x[:2, -1])

tensor([3, 7])
